name: fedodo_ui_photo
description: Photos for Fedodo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  activitypub: ^1.1.2
  fedodo_general: ^1.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/fedodo_general/Fonts/Roboto/Roboto-Regular.ttf
        - asset: packages/fedodo_general/Fonts/Roboto/Roboto-Black.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: packages/fedodo_general/Fonts/NotoColorEmoji-Regular.ttf
    - family: Righteous
      fonts:
        - asset: packages/fedodo_general/Fonts/Righteous-Regular.ttf
  uses-material-design: true